services:
  - type: web
    name: velosi-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_ADDR
        value: aws-1-eu-north-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres.aswqsbrpkofmhgqjmyuw
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        value: postgres
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: KEYCLOAK_URL
        value: http://localhost:8080
      - key: KEYCLOAK_REALM
        value: ERP_Velosi
      - key: KEYCLOAK_CLIENT_ID
        value: velosi_auth
      - key: KEYCLOAK_CLIENT_SECRET
        sync: false
